[workspace]
resolver = "2"
members = [
    "subnet",
    # "movement",
    # "movement-benchmark",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Liam Monninger <liam@movementlabs.xyz>"]
homepage = "https://www.movementlabs.xyz"
publish = false
repository = "https://github.com/movemntdev/m2"
rust-version = "1.66"

[workspace.dependencies]
anyhow = "1.0.62"
futures = "0.3.28"
rand = { version =  "0.7.3" }
bcs = { git = "https://github.com/aptos-labs/bcs.git", rev = "d31fab9d81748e2594be5cd5cdf845786a30562d" }

# aptos
# TODO: pleas remove unused dependencies
aptos = { path = "../aptos-pre-core/crates/aptos" }
aptos-accumulator = { path = "../aptos-pre-core/storage/accumulator" }
aptos-aggregator = { path = "../aptos-pre-core/aptos-move/aptos-aggregator" }
aptos-api = { path = "../aptos-pre-core/api" }
aptos-api-test-context = { path = "../aptos-pre-core/api/test-context" }
aptos-api-types = { path = "../aptos-pre-core/api/types" }
aptos-backup-cli = { path = "../aptos-pre-core/storage/backup/backup-cli" }
aptos-backup-service = { path = "../aptos-pre-core/storage/backup/backup-service" }
aptos-bounded-executor = { path = "../aptos-pre-core/crates/bounded-executor" }
aptos-block-executor = { path = "../aptos-pre-core/aptos-move/block-executor" }
aptos-bitvec = { path = "../aptos-pre-core/crates/aptos-bitvec" }
aptos-build-info = { path = "../aptos-pre-core/crates/aptos-build-info" }
aptos-cached-packages = { path = "../aptos-pre-core/aptos-move/framework/cached-packages" }
aptos-channels = { path = "../aptos-pre-core/crates/channel" }
aptos-cli-common = { path = "../aptos-pre-core/crates/aptos-cli-common" }
aptos-compression = { path = "../aptos-pre-core/crates/aptos-compression" }
aptos-consensus = { path = "../aptos-pre-core/consensus" }
aptos-consensus-notifications = { path = "../aptos-pre-core/state-sync/inter-component/consensus-notifications" }
aptos-consensus-types = { path = "../aptos-pre-core/consensus/consensus-types" }
aptos-config = { path = "../aptos-pre-core/config" }
aptos-crash-handler = { path = "../aptos-pre-core/crates/crash-handler" }
aptos-crypto = { path = "../aptos-pre-core/crates/aptos-crypto" }
aptos-crypto-derive = { path = "../aptos-pre-core/crates/aptos-crypto-derive" }
aptos-data-client = { path = "../aptos-pre-core/state-sync/aptos-data-client" }
aptos-data-streaming-service = { path = "../aptos-pre-core/state-sync/state-sync-v2/data-streaming-service" }
aptos-db = { path = "../aptos-pre-core/storage/aptosdb" }
aptos-db-indexer = { path = "../aptos-pre-core/storage/indexer" }
aptos-db-tool = { path = "../aptos-pre-core/storage/db-tool" }
aptos-debugger = { path = "../aptos-pre-core/aptos-move/aptos-debugger" }
aptos-event-notifications = { path = "../aptos-pre-core/state-sync/inter-component/event-notifications" }
aptos-executable-store = { path = "../aptos-pre-core/storage/executable-store" }
aptos-executor = { path = "../aptos-pre-core/execution/executor" }
aptos-block-partitioner = { path = "../aptos-pre-core/execution/block-partitioner" }
aptos-enum-conversion-derive = { path = "../aptos-pre-core/crates/aptos-enum-conversion-derive" }
aptos-executor-service = { path = "../aptos-pre-core/execution/executor-service" }
aptos-executor-test-helpers = { path = "../aptos-pre-core/execution/executor-test-helpers" }
aptos-executor-types = { path = "../aptos-pre-core/execution/executor-types" }
aptos-faucet-cli = { path = "../aptos-pre-core/crates/aptos-faucet/cli" }
aptos-faucet-core = { path = "../aptos-pre-core/crates/aptos-faucet/core" }
aptos-faucet-service = { path = "../aptos-pre-core/crates/aptos-faucet/service" }
aptos-faucet-metrics-server = { path = "../aptos-pre-core/crates/aptos-faucet/metrics-server" }
aptos-fallible = { path = "../aptos-pre-core/crates/fallible" }
aptos-forge = { path = "../aptos-pre-core/testsuite/forge" }
aptos-framework = { path = "../aptos-pre-core/aptos-move/framework" }
aptos-fuzzer = { path = "../aptos-pre-core/testsuite/aptos-fuzzer" }
fuzzer = { path = "../aptos-pre-core/testsuite/fuzzer" }
aptos-gas = { path = "../aptos-pre-core/aptos-move/aptos-gas" }
aptos-gas-algebra-ext = { path = "../aptos-pre-core/aptos-move/gas-algebra-ext" }
aptos-gas-profiling = { path = "../aptos-pre-core/aptos-move/aptos-gas-profiling" }
aptos-genesis = { path = "../aptos-pre-core/crates/aptos-genesis" }
aptos-github-client = { path = "../aptos-pre-core/crates/aptos-github-client" }
aptos-global-constants = { path = "../aptos-pre-core/config/global-constants" }
aptos-id-generator = { path = "../aptos-pre-core/crates/aptos-id-generator" }
aptos-indexer = { path = "../aptos-pre-core/crates/indexer" }
aptos-indexer-grpc-cache-worker = { path = "../aptos-pre-core/ecosystem/indexer-grpc/indexer-grpc-cache-worker" }
aptos-indexer-grpc-data-service = { path = "../aptos-pre-core/ecosystem/indexer-grpc/indexer-grpc-data-service" }
aptos-indexer-grpc-file-store = { path = "../aptos-pre-core/ecosystem/indexer-grpc/indexer-grpc-file-store" }
aptos-indexer-grpc-post-processor = { path = "../aptos-pre-core/ecosystem/indexer-grpc/indexer-grpc-post-processor" }
aptos-indexer-grpc-fullnode = { path = "../aptos-pre-core/ecosystem/indexer-grpc/indexer-grpc-fullnode" }
aptos-indexer-grpc-utils = { path = "../aptos-pre-core/ecosystem/indexer-grpc/indexer-grpc-utils" }
aptos-indexer-grpc-parser = { path = "../aptos-pre-core/ecosystem/indexer-grpc/indexer-grpc-parser" }
aptos-indexer-grpc-server-framework = { path = "../aptos-pre-core/ecosystem/indexer-grpc/indexer-grpc-server-framework" }
aptos-infallible = { path = "../aptos-pre-core/crates/aptos-infallible" }
aptos-inspection-service = { path = "../aptos-pre-core/crates/aptos-inspection-service" }
aptos-jellyfish-merkle = { path = "../aptos-pre-core/storage/jellyfish-merkle" }
aptos-keygen = { path = "../aptos-pre-core/crates/aptos-keygen" }
aptos-language-e2e-tests = { path = "../aptos-pre-core/aptos-move/e2e-tests" }
aptos-ledger = { path = "../aptos-pre-core/crates/aptos-ledger" }
aptos-log-derive = { path = "../aptos-pre-core/crates/aptos-log-derive" }
aptos-logger = { path = "../aptos-pre-core/crates/aptos-logger" }
aptos-memory-usage-tracker = { path = "../aptos-pre-core/aptos-move/aptos-memory-usage-tracker" }
aptos-mempool = { path = "../aptos-pre-core/mempool" }
aptos-mempool-notifications = { path = "../aptos-pre-core/state-sync/inter-component/mempool-notifications" }
aptos-memsocket = { path = "../aptos-pre-core/network/memsocket" }
aptos-metrics-core = { path = "../aptos-pre-core/crates/aptos-metrics-core" }
aptos-move-examples = { path = "../aptos-pre-core/aptos-move/move-examples" }
aptos-moving-average = { path = "../aptos-pre-core/crates/moving-average" }
aptos-mvhashmap = { path = "../aptos-pre-core/aptos-move/mvhashmap" }
aptos-netcore = { path = "../aptos-pre-core/network/netcore" }
aptos-network = { path = "../aptos-pre-core/network" }
aptos-network-builder = { path = "../aptos-pre-core/network/builder" }
aptos-network-checker = { path = "../aptos-pre-core/crates/aptos-network-checker" }
aptos-network-discovery = { path = "../aptos-pre-core/network/discovery" }
aptos-node = { path = "../aptos-pre-core/aptos-node" }
aptos-node-checker = { path = "../aptos-pre-core/ecosystem/node-checker" }
aptos-node-identity = { path = "../aptos-pre-core/crates/aptos-node-identity" }
aptos-node-resource-metrics = { path = "../aptos-pre-core/crates/node-resource-metrics" }
aptos-num-variants = { path = "../aptos-pre-core/crates/num-variants" }
aptos-openapi = { path = "../aptos-pre-core/crates/aptos-openapi" }
aptos-package-builder = { path = "../aptos-pre-core/aptos-move/package-builder" }
aptos-peer-monitoring-service-client = { path = "../aptos-pre-core/network/peer-monitoring-service/client" }
aptos-peer-monitoring-service-server = { path = "../aptos-pre-core/network/peer-monitoring-service/server" }
aptos-peer-monitoring-service-types = { path = "../aptos-pre-core/network/peer-monitoring-service/types" }
aptos-proptest-helpers = { path = "../aptos-pre-core/crates/aptos-proptest-helpers" }
aptos-protos = { path = "../aptos-pre-core/crates/aptos-protos" }
aptos-proxy = { path = "../aptos-pre-core/crates/proxy" }
aptos-push-metrics = { path = "../aptos-pre-core/crates/aptos-push-metrics" }
aptos-rate-limiter = { path = "../aptos-pre-core/crates/aptos-rate-limiter" }
aptos-release-builder = { path = "../aptos-pre-core/aptos-move/aptos-release-builder" }
aptos-resource-viewer = { path = "../aptos-pre-core/aptos-move/aptos-resource-viewer" }
aptos-rest-client = { path = "../aptos-pre-core/crates/aptos-rest-client" }
aptos-retrier = { path = "../aptos-pre-core/crates/aptos-retrier" }
aptos-rocksdb-options = { path = "../aptos-pre-core/storage/rocksdb-options" }
aptos-rosetta = { path = "../aptos-pre-core/crates/aptos-rosetta" }
aptos-runtimes = { path = "../aptos-pre-core/crates/aptos-runtimes" }
aptos-safety-rules = { path = "../aptos-pre-core/consensus/safety-rules" }
aptos-schemadb = { path = "../aptos-pre-core/storage/schemadb" }
aptos-scratchpad = { path = "../aptos-pre-core/storage/scratchpad" }
aptos-sdk = { path = "../aptos-pre-core/sdk" }
aptos-sdk-builder = { path = "../aptos-pre-core/aptos-move/aptos-sdk-builder" }
aptos-secure-net = { path = "../aptos-pre-core/secure/net" }
aptos-secure-storage = { path = "../aptos-pre-core/secure/storage" }
aptos-short-hex-str = { path = "../aptos-pre-core/crates/short-hex-str" }
aptos-speculative-state-helper = { path = "../aptos-pre-core/crates/aptos-speculative-state-helper" }
aptos-state-sync-driver = { path = "../aptos-pre-core/state-sync/state-sync-v2/state-sync-driver" }
aptos-state-view = { path = "../aptos-pre-core/storage/state-view" }
aptos-storage-interface = { path = "../aptos-pre-core/storage/storage-interface" }
aptos-storage-service-client = { path = "../aptos-pre-core/state-sync/storage-service/client" }
aptos-storage-service-notifications = { path = "../aptos-pre-core/state-sync/inter-component/storage-service-notifications" }
aptos-storage-service-types = { path = "../aptos-pre-core/state-sync/storage-service/types" }
aptos-storage-service-server = { path = "../aptos-pre-core/state-sync/storage-service/server" }
aptos-telemetry = { path = "../aptos-pre-core/crates/aptos-telemetry" }
aptos-telemetry-service = { path = "../aptos-pre-core/crates/aptos-telemetry-service" }
aptos-temppath = { path = "../aptos-pre-core/crates/aptos-temppath" }
aptos-testcases = { path = "../aptos-pre-core/testsuite/testcases" }
aptos-time-service = { path = "../aptos-pre-core/crates/aptos-time-service", features = [
    "async",
] }
aptos-transaction-emitter-lib = { path = "../aptos-pre-core/crates/transaction-emitter-lib" }
aptos-transaction-generator-lib = { path = "../aptos-pre-core/crates/transaction-generator-lib" }
aptos-transactional-test-harness = { path = "../aptos-pre-core/aptos-move/aptos-transactional-test-harness" }
aptos-types = { path = "../aptos-pre-core/types" }
aptos-utils = { path = "../aptos-pre-core/aptos-utils" }
aptos-validator-interface = { path = "../aptos-pre-core/aptos-move/aptos-validator-interface" }
aptos-vault-client = { path = "../aptos-pre-core/secure/storage/vault" }
aptos-vm = { path = "../aptos-pre-core/aptos-move/aptos-vm" }
aptos-vm-logging = { path = "../aptos-pre-core/aptos-move/aptos-vm-logging" }
aptos-vm-genesis = { path = "../aptos-pre-core/aptos-move/vm-genesis" }
aptos-vm-types = { path = "../aptos-pre-core/aptos-move/aptos-vm-types" }
aptos-vm-validator = { path = "../aptos-pre-core/vm-validator" }
aptos-warp-webserver = { path = "../aptos-pre-core/crates/aptos-warp-webserver" }
aptos-writeset-generator = { path = "../aptos-pre-core/aptos-move/writeset-transaction-generator" }