name: Cargo Check

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: 
      labels: movement-runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.70.0

      - name: Install build essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}-v4
    
      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}-v4

      - name: Run Cargo Check
        working-directory: ./m1  
        run: cargo check

