name: Cargo Check

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: 
      labels: movement-runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install build essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential lld

      - name: Print Linker Version
        run: ld --version
        
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.70

      - name: Run Cargo Check
        working-directory: ./m1  
        run: cargo check

