name: Run Movement Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: movemntdev/movement-hack

    - name: Execute install script
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/movemntdev/M1/main/scripts/install.sh) --latest
        echo "~/.movement/bin" >> $GITHUB_PATH

    - name: Navigate and Run Movement Test
      run: |
        echo $GITHUB_PATH
        cd examples/movement/data_structures
        movement move test
