name: Binary Release

on:
  workflow_run:
    workflows: ["Cargo Check"]
    types: 
      - completed

jobs:
  build:
    runs-on: 
      labels: movement-runner
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'  # Ensures submodules are fetched

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Install windows target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Install mac target
        run: rustup target add x86_64-apple-darwin

      - name: Install aarch64 target
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Run dev setup script
        run: |
          cd "$GITHUB_WORKSPACE/aptos-pre-core"
          chmod -R 755 ./scripts
          echo "yes" | ./scripts/dev_setup.sh

      - name: Build binaries
        run: |
          cd "$GITHUB_WORKSPACE/m1"
          RUSTFLAGS="--cfg tokio_unstable" cargo build --release
          
      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            $GITHUB_WORKSPACE/m1/target/release/*
